ASP_Decisions/Controllers/DecisionController.cs
using ASP_Decisions_v1.Epo_facade;
using ASP_Decisions_v1.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ASP_Decisions_v1.Controllers
{
    public class DecisionController : Controller
    {
        private DecisionDbContext db = new DecisionDbContext();

        // GET: Decisions
        public ActionResult Index()
        {
            return View(db.Decisions.ToList());
        }

        // GET: Decisions/Details/5
        public async Task<ActionResult> Details(int? id)
        {
           if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Decision decision = db.Decisions.Find(id);
            if (decision == null)
            {
                return HttpNotFound();
            }

            List<Decision> citedDecisions = new List<Decision>();
            if (decision.CitedCases != "")
                citedDecisions = await _getCited(decision);
            ViewBag.CitedDecisions = citedDecisions;

            if (!decision.TextDownloaded)
            {
                EpoSearch.GetDecisionText(decision);
                db.SaveChanges();
            }

            ViewBag.Facts = decision.Facts.Split(new string[] { "\n\n" }, StringSplitOptions.RemoveEmptyEntries);
            ViewBag.Reasons = decision.Reasons.Split(new string[] { "\n\n" }, StringSplitOptions.RemoveEmptyEntries);
            ViewBag.Order = decision.Order.Split(new string[] { "\n\n" }, StringSplitOptions.RemoveEmptyEntries);

            return View(decision);
        }

        // GET: Decisions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Decisions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CaseNumber,MetaDownloaded,DecisionDate,OnlineDate,Applicant,Opponents,Appellants,Respondents,ApplicationNumber,Ipc,Title,ProcedureLanguage,Board,Keywords,Articles,Rules,Ecli,CitedCases,Distribution,Headword,Catchwords,DecisionLanguage,Link,PdfLink,TextDownloaded,HasSplitText,FactHeader,ReasonsHeader,OrderHeader,Facts,Reasons,Order")] Decision decision)
        {
            if (ModelState.IsValid)
            {
                db.Decisions.Add(decision);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(decision);
        }

        // GET: Decisions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Decision decision = db.Decisions.Find(id);
            if (decision == null)
            {
                return HttpNotFound();
            }
            return View(decision);
        }

        // POST: Decisions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CaseNumber,MetaDownloaded,DecisionDate,OnlineDate,Applicant,Opponents,Appellants,Respondents,ApplicationNumber,Ipc,Title,ProcedureLanguage,Board,Keywords,Articles,Rules,Ecli,CitedCases,Distribution,Headword,Catchwords,DecisionLanguage,Link,PdfLink,TextDownloaded,HasSplitText,FactHeader,ReasonsHeader,OrderHeader,Facts,Reasons,Order")] Decision decision)
        {
            if (ModelState.IsValid)
            {
                db.Entry(decision).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(decision);
        }

        // GET: Decisions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Decision decision = db.Decisions.Find(id);
            if (decision == null)
            {
                return HttpNotFound();
            }
            return View(decision);
        }

        // POST: Decisions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Decision decision = db.Decisions.Find(id);
            db.Decisions.Remove(decision);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        #region helper methods
        private async Task<List<Decision>> _getCited(Decision decision)
        {
            List<Decision> citedDecisions = new List<Decision>();

            foreach (string cited in decision.CitedCases.Split(','))
            {
                string ctd = cited.Trim();
                Decision inDB = db.Decisions.FirstOrDefault(
                    dec => dec.CaseNumber == ctd
                            && dec.DecisionLanguage == dec.ProcedureLanguage);

                if (inDB != null)
                {
                    citedDecisions.Add(inDB);
                }
                else
                {
                    // we don't have this decision yet
                    // or decision has a typo?
                    // try to find it on the EPO site; if we do,
                    // add it to the DB

                    List<Decision> fromEPO = await Epo_facade.EpoSearch.SearchCaseNumberAsync(ctd);
                    if (fromEPO == null || fromEPO.Count == 0)
                    {
                        citedDecisions.Add(new Decision() { CaseNumber = ctd, Title = "Not found" });
                        continue;
                    }
                    
                    bool added = false;
                    foreach (Decision dec in fromEPO)
                    {
                        db.AddOrUpdate(dec);
                        if (dec.DecisionLanguage == dec.ProcedureLanguage && !added)
                        {
                            citedDecisions.Add(dec);
                            added = true;
                        }
                    }
                    if (!added)
                        citedDecisions.Add(fromEPO.First());
                }
            }

            return citedDecisions;
        }
        #endregion

    }
}

ASP_Decisions/Views/Decision/Details.cshtml
@model ASP_Decisions_v1.Models.Decision

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <div class="row">
        <div class="col-sm-4" id="bibl-display-parent">
            <div class="bibl-display" id="bibl-display-div" data-spy="affix">
                <h1 class="casenumber"> @Html.DisplayFor(model => model.CaseNumber) </h1>
                <p class="headword"> @Html.DisplayFor(model => model.Headword) </p>
                <p class="ECLI"> @Html.DisplayFor(model => model.Ecli) </p>
                <p class="date+board">
                    @Html.DisplayFor(model => model.DecisionDate)
                    by board 
                    @Html.DisplayFor(model => model.Board)
                    @if (Model.OnlineDate != null)
                    {
                        @:(online since 
                        @Html.DisplayFor(model => model.OnlineDate);
                        @:)
                    }
                </p>
                <h4 class="title"> @Html.DisplayFor(model => model.Title) </h4>
                <p class="applicant"> @Html.DisplayFor(model => model.Applicant) </p>
                @if (Model.Opponents != "")
                    { <p class="opponents">Opponents: @Html.DisplayFor(model => model.Opponents) </p> }
                @if (Model.Articles != "")
                    { <p class="articles+rules"> Article(s) @Html.DisplayFor(model => model.Articles) </p> }
                @if (Model.Rules != "")
                    { <p class="articles+rules"> Rules: @Html.DisplayFor(model => model.Rules) </p> }
                @*<p class="keywords">*@
                @if (ViewBag.CitedDecisions.Count > 0)
                {
                    <p>
                        Cited decisions:
                        @foreach (var cited in ViewBag.CitedDecisions)
                        {
                            <a href=@Url.Action("Details", "Decision", new { id = cited.Id })>
                                @cited.CaseNumber.Replace(' ', '\u00A0')
                            </a>
                        }
                    </p>
                }
</div>
        </div>



        <div class="col-sm-8">
            <ul class="nav nav-tabs">
                <li><a data-toggle="tab" href="#procedure">Procedure</a></li>
                <li class="active"><a data-toggle="tab" href="#reasons">Reasons</a></li>
                <li><a data-toggle="tab" href="#outcome">Outcome</a></li>
                <li><a data-toggle="tab" href="#comments">Comments</a></li>
            </ul>

            <div class="tab-content">
                <div id="procedure" class="tab-pane fade">
                    <h4> @Model.FactsHeader </h4>
                    @foreach (var para in ViewBag.Facts) { <p> @para </p> }
                </div>
                <div id="reasons" class="tab-pane fade in active">
                    <h4> @Model.ReasonsHeader </h4>
                    @foreach (var para in ViewBag.Reasons) { <p> @para </p> }                    
                </div>
                <div id="outcome" class="tab-pane fade">
                    <h4> @Model.OrderHeader </h4>
                    @foreach (var para in ViewBag.Order) { <p> @para </p> }
                </div>
                <div id="comments" class="tab-pane fade">
                    <h4> Comments </h4>
                    <p> There might be comments, one day. </p>
                </div>
            </div>



        </div>
    </div>
</div>

<script>
    /* Responsive width when using the bootstrap affix plugin (width became absolute) with a fluid grid */
    $(function(){
    var biblDisplayWidth=$('#bibl-display-parent').width();
    $('#bibl-display-div').css('width', biblDisplayWidth);
    });
</script>